### ISSUE TITLE
found bug when launching create comment modal

### ISSUE THREAD

**Issue by FerreroFacundo** [wejs/we-plugin-comment#2]
From the groups plugin I found that when you try to create a new comment for a post, I got this error:

_/comment-form/post/2 Error: Not Acceptable_

this is becausse the responseType was being overwritten in the router file:
[we-core/lib/Router/index.js](https://github.com/wejs/we-core/blob/master/lib/Router/index.js#L596)

line 596
**if (config.responseType) req.headers.accept = mime.lookup(config.responseType);**

when you set the route in plugin.js in the comment [plugin.js](https://github.com/wejs/we-plugin-comment/blob/master/plugin.js#L24) file like this:

  plugin.setRoutes({
      'get /comment-form/:modelName/:modelId': {
          controller: 'comment',
          action: 'getCommentForm',
          template: 'comment/commentForm',
          **_responseType: 'modal'_**
        }
  });

the highlighted line forces to overwrite the mime type, so it searches for the mime type "modal"; since this mime type does not exists, it uses the default value "application/octect-stream", and this is not an acceptable format for the layout formatter for this url.

So the workaround I found is this:
1. comment the **_responseType: 'modal'_** line in plugin.js
2. add the following line to [we-plugin-comment/files/public/comment.js](https://github.com/wejs/we-plugin-comment/blob/master/files/public/comment.js#L19)
   Right after line 18
   _url += '?redirectTo='+location.pathname;_
   add:
   **_url += '&responseType=modal';_**

I tried checking the tests, but they are not working (and also I tried this solution running under Ubuntu, Windows with chrome & Firefox and it works)

**Comment by albertosouza** [comment]
@FerreroFacundo thanks, may be response format API ... now is possible to select data format with extensions in url.

I will test this plugin with we.js v1.2.x and fix this now

**Comment by FerreroFacundo** [comment]
excelente trabalho com este framework, Alberto. Vou tentar colaborar as vezes que seja possible

**Comment by albertosouza** [comment]
fixed in https://github.com/wejs/we-plugin-comment/commit/d7aa8c781dc4089053d71911aa10659a24b591d8

Pode atualizar com: `npm install we-plugin-comment@1.0.2`

Essa API de comentários precisa de melhorias ... vou tentar melhorar ela hoje de noite ou amanhã para rescrever a API com Custom elements que está disponível no we.js  v1.2.x

**Comment by albertosouza** [comment]
E @FerreroFacundo obrigado, reports e comentários ajudam bastante.

Falta trabalho em coisas mais simples como a documentação ... o We.js hoje tem muitos recursos e uma API rica para criar sites com APIs integradas mas isso demanda uma documentação grande.

**Comment by albertosouza** [comment]
ref https://github.com/wejs/we-plugin-comment/issues/3
